[build]
  functions = "functions"
  publish = "public"

[[redirects]]
  from = "/shared_post*"
  to = "/.netlify/functions/share"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
